title: Blog
author:
  name: Delta6862

description: >
  Student and occasional CTF player mostly interested in InfoSec and computing. 

theme: minima

minima:
  social_links:
    - { platform: github,         user_url: "https://github.com/delta6862" }
    - { platform: twitter,        user_url: "https://twitter.com/delta6862" }

header_pages:
 - README.md